### ISSUE TITLE
bp leaderboard crash servers

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/battle-pass#558] opened 2024-07-12 10:36 UTC
### Describe the bug

when I run the command my server crashes

### How to reproduce

use /bp leadeboard

### Server Log

https://mclo.gs/UihnQwe

**Comment by KPGTB** [comment] 2024-07-12 12:00
Hey! I can't reproduce this problem - everything works fine on my test server, but I made a small refactor in leaderboard controller (in the method which caused this crash) and maybe it'll fix that problem. Probably the next update will add this change, so after that I'll let you know. Please check after update if problem will be fixed.

**Comment by Z3r0xh** [comment] 2024-07-13 11:12
> Hey! I can't reproduce this problem - everything works fine on my test server, but I made a small refactor in leaderboard controller (in the method which caused this crash) and maybe it'll fix that problem. Probably the next update will add this change, so after that I'll let you know. Please check after update if problem is fixed.

I have the latest version uploaded today, the problem persists.

https://mclo.gs/TyUm3w0

**Comment by KPGTB** [comment] 2024-07-13 13:10
Hey! I need more info to reproduce this error. 

1) Do you use file storage or mysql?
2) Can you send me users storage? If you use files method, just send me folder `users` (or `users-storage`) from BattlePass folder. If you use mysql, please export bp users table. If you don't want to send it here, just send me it on discord `kpgtb`
3) Where do you host your server and which hosting plan do you use? 
4) Can you try to test plugin locally (making server on own computer)
5) Can you try plugin with only placeholderapi? (wothout any other plugin)

We need to find what causes that problem, because on clean local server everything works fine

**Comment by Z3r0xh** [comment] 2024-07-13 13:32
> Hey! I need more info to reproduce this error.
> 
> 1. Do you use file storage or mysql?
> 2. Can you send me users storage? If you use files method, just send me folder `users` (or `users-storage`) from BattlePass folder. If you use mysql, please export bp users table. If you don't want to send it here, just send me it on discord `kpgtb`
> 3. Where do you host your server and which hosting plan do you use?
> 4. Can you try to test plugin locally (making server on own computer)
> 5. Can you try plugin with only placeholderapi? (wothout any other plugin)
> 
> We need to find what causes that problem, because on clean local server everything works fine

1. I use mysql
2. I'll leave it in the discord ticket for you.
3. 3. bloom performance+
4. Right now it is impossible for me because I am not working with my personal PC.
5. same problem

**Comment by Z3r0xh** [comment] 2024-07-14 12:39
> Hey! I need more info to reproduce this error.
> 
> 1. Do you use file storage or mysql?
> 2. Can you send me users storage? If you use files method, just send me folder `users` (or `users-storage`) from BattlePass folder. If you use mysql, please export bp users table. If you don't want to send it here, just send me it on discord `kpgtb`
> 3. Where do you host your server and which hosting plan do you use?
> 4. Can you try to test plugin locally (making server on own computer)
> 5. Can you try plugin with only placeholderapi? (wothout any other plugin)
> 
> We need to find what causes that problem, because on clean local server everything works fine

It is a problem with the database, after trying a clean installation and everything is fine. It has been connecting the plugin to the database that it already had for 2 months and this error remains.

**Comment by Z3r0xh** [comment] 2024-07-14 13:38
https://mclo.gs/zvmCtTm

**Comment by KPGTB** [comment] 2024-07-14 20:27
Hey! I fixed a bug which caused server crashing. It will be merged & uploaded to download platforms asap. 

According to your last comment about `Duplicate entry` error. When it happened? Also, did you have any other errors? It's still showing after server restart? If yes, please provide more details in a new issue - it's not related to crash bug and this issue will be automatically closed when GC merge my PR.

**Sorry for these problems with our plugin,**
_KPG-TB_

**Closed** 2024-07-15 08:20 UTC
Labels: Status: Resolved, Critical, Bug: Confirmed
