### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by neviskcubo** [GC-spigot/battle-pass#569] opened 2024-08-01 07:46 UTC
### Describe the bug

https://mclo.gs/Xlv162D

### How to reproduce

use bpadmin reload and server will freeze

**Comment by KPGTB** [comment] 2024-08-03 12:33
Hey! I can't reproduce this error, but I made some changes in classes which caused this crash and maybe after next update it will be fixed. After update, please install the latest version and let me know if it resolves your problem.

**Closed** 2024-08-11 09:24 UTC
Labels: Bug: Unconfirmed, Status: Resolved
