### ISSUE TITLE
[Request] Adding edit of admin command

### ISSUE THREAD

**Issue by RookieAND** [GC-spigot/battle-pass#89] opened 2021-09-25 08:34 UTC
**Describe the Request**

In BattlePass, player can edit normal message of battlepass but they cannot edit admin command message like /bpa progress or /bpa reset.

I use command to add progress of some quest. But It spams message in console when command has been executed by console. So I suggest to handle it.

**Comment by OpticFusion1** [comment] 2023-03-17 19:13
Closed. Duplicate of #88

**Closed by OpticFusion1** 2023-03-17 19:13 UTC
Labels: Request
