### ISSUE TITLE
Old bug happening for months

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/battle-pass#555] opened 2024-07-07 08:37 UTC
### Describe the bug

Every time /bpa reload is used it crashes the server... 

### How to reproduce

Every time /bpa reload is used it crashes the server... 

### Screenshots / Videos

Every time /bpa reload is used it crashes the server... 

### Server Log

Every time /bpa reload is used it crashes the server...

**Comment by KPGTB** [comment] 2024-07-07 17:52
Hey! Which battlepass version do you use? Also can you send me logs? Where do you host your server?

**Comment by bennes2004** [comment] 2024-07-15 18:48
Hey, also having the same issue, reloading battlepass crashes the server. And using /bp leaderboard does the same thing, please help! 

Battlepass Version : 4.5.6
[message.txt](https://github.com/user-attachments/files/16238888/message.txt) <-- Error that shows when doing /bp leaderboard, similar to /bpa reload error

**Comment by bennes2004** [comment] 2024-07-16 17:29
Even after reinstalling, it still gives an error when reloading

[10:28:00 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Axolotl-"228c3df" (MC: 1.20.4) ---
[10:28:00 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[10:28:00 ERROR]: ------------------------------
[10:28:00 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:28:00 ERROR]: ------------------------------
[10:28:00 ERROR]: Current Thread: Server thread
[10:28:00 ERROR]:       PID: 83 | Suspended: false | Native: false | State: RUNNABLE
[10:28:00 ERROR]:       Stack:
[10:28:00 ERROR]:               java.base@21.0.3/java.io.DataInputStream.readUTF(DataInputStream.java:600)
[10:28:00 ERROR]:               java.base@21.0.3/java.io.DataInputStream.readUTF(DataInputStream.java:550)
[10:28:00 ERROR]:               net.minecraft.nbt.StringTag$1.readAccounted(StringTag.java:23)
[10:28:00 ERROR]:               net.minecraft.nbt.StringTag$1.load(StringTag.java:13)
[10:28:00 ERROR]:               net.minecraft.nbt.StringTag$1.load(StringTag.java:13)
[10:28:00 ERROR]:               net.minecraft.nbt.ListTag$1.loadList(ListTag.java:45)
[10:28:00 ERROR]:               net.minecraft.nbt.ListTag$1.load(ListTag.java:24)
[10:28:00 ERROR]:               net.minecraft.nbt.ListTag$1.load(ListTag.java:16)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:528)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.loadCompound(CompoundTag.java:57)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:42)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:35)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:528)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.loadCompound(CompoundTag.java:57)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:42)
[10:28:00 ERROR]:               net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:35)
[10:28:00 ERROR]:               net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:382)
[10:28:00 ERROR]:               net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:376)
[10:28:00 ERROR]:               net.minecraft.nbt.NbtIo.read(NbtIo.java:306)
[10:28:00 ERROR]:               net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:73)
[10:28:00 ERROR]:               net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:39)
[10:28:00 ERROR]:               net.minecraft.world.level.storage.PlayerDataStorage.getPlayerData(PlayerDataStorage.java:113)
[10:28:00 ERROR]:               org.bukkit.craftbukkit.v1_20_R3.CraftOfflinePlayer.getData(CraftOfflinePlayer.java:210)
[10:28:00 ERROR]:               org.bukkit.craftbukkit.v1_20_R3.CraftOfflinePlayer.getBukkitData(CraftOfflinePlayer.java:214)
[10:28:00 ERROR]:               org.bukkit.craftbukkit.v1_20_R3.CraftOfflinePlayer.getName(CraftOfflinePlayer.java:76)
[10:28:00 ERROR]:               BattlePass-4.5.6.jar//io.github.battlepass.commands.bpadmin.BoosterAddCommand$$Lambda/0x00007f2dc81432f0.apply(Unknown Source)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:28:00 ERROR]:               java.base@21.0.3/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:28:00 ERROR]:               BattlePass-4.5.6.jar//io.github.battlepass.commands.bpadmin.BoosterAddCommand.<init>(BoosterAddCommand.java:26)
[10:28:00 ERROR]:               BattlePass-4.5.6.jar//io.github.battlepass.commands.bpadmin.BpaCommand.<init>(BpaCommand.java:30)
[10:28:00 ERROR]:               BattlePass-4.5.6.jar//io.github.battlepass.BattlePlugin.lambda$load$3(BattlePlugin.java:349)
[10:28:00 ERROR]:               BattlePass-4.5.6.jar//io.github.battlepass.BattlePlugin$$Lambda/0x00007f2dc79ff530.run(Unknown Source)
[10:28:00 ERROR]:               org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[10:28:00 ERROR]:               org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[10:28:00 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1668)
[10:28:00 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:458)
[10:28:00 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1547)
[10:28:00 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242)
[10:28:00 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[10:28:00 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda/0x00007f2dc4b8fa50.run(Unknown Source)
[10:28:00 ERROR]:               java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
[10:28:00 ERROR]:               java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
[10:28:00 ERROR]: ------------------------------
[10:28:00 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:28:00 ERROR]: ------------------------------
[10:28:05 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Axolotl-"228c3df" (MC: 1.20.4) ---
[10:28:05 ERROR]: The server has not responded for 15 seconds! Creating thread dump
[10:28:05 ERROR]: ------------------------------
[10:28:05 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:28:05 ERROR]: ------------------------------
[10:28:05 ERROR]: Current Thread: Server thread

**Comment by bennes2004** [comment] 2024-07-16 17:54
Using (/bpa boosters) also causes a Timed Out error to occur on the player that uses it

**Comment by KPGTB** [comment] 2024-07-16 20:08
Leaderboards have been fixed in 4.5.8

**Comment by KPGTB** [comment] 2024-07-16 20:19
For other bugs, please send me:

- server hosting & hosting plan (if localhost - how much RAM do you have assigned to server)
- logs from executing each command which causes crash
- user data (if you use mysql, please export table `battlepass_users`. If you use file save method, please send me folder `plugins/BattlePass/users`). If you don't want to share it here, please send me this on discord `kpgtb`
- minecraft player data (`usercache.json` from server root directory and `world/playerdata` folder) Same as user data - you can send it here or on discord

I can't reproduce your problems on my server, so maybe these files will help me to reproduce that 😉
Also, please update plugin to the latest version and check leaderboards problem again.

**Comment by bennes2004** [comment] 2024-07-25 19:28
Apologies, not been able to get on to do the stuff asked for, just can give some more info. Turns out the server doesnt crash when using /bp leaderboards or /bpa reload. but instead causes the server to lag and pretty much freeze up for around 800-1000 ticks, and then times out players on the server, it even does this when I am the only player online

**Comment by KPGTB** [comment] 2024-07-28 12:21
Hey! I'm sorry, but without users data, I can't help you, because I can't reproduce this problem.

**Comment by KPGTB** [comment] 2024-08-18 15:30
Closed due to no response

**Closed by KPGTB** 2024-08-18 15:30 UTC
Labels: Bug: Unconfirmed, Bug: Can't Reproduce, Status: Awaiting Response
