### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by cat-catmiao** [GC-spigot/battle-pass#570] opened 2024-08-01 15:45 UTC
### Describe the bug

My server version is paper 1.21 and when I start the server I get this error and I can't use the plugin
`[23:40:26 INFO]: [BattlePass] Successfully loaded the pass type with the id: free
[23:40:26 INFO]: [BattlePass] Successfully loaded the pass type with the id: premium
[23:40:26 ERROR]: Error occurred while enabling BattlePass v4.6.1 (Is it up to date?)
java.lang.IllegalArgumentException: TypeToken type argument must not contain a type variable; captured type variable T declared by public static java.lang.reflect.Type me.hyfe.simplespigot.json.TypeTokens.findType()
See https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable
        at com.google.gson.reflect.TypeToken.verifyNoTypeVariable(TypeToken.java:130) ~[gson-2.11.0.jar:?]
        at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:103) ~[gson-2.11.0.jar:?]
        at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:74) ~[gson-2.11.0.jar:?]
        at BattlePass-4.6.1.jar/me.hyfe.simplespigot.json.TypeTokens$1.<init>(TypeTokens.java:10) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/me.hyfe.simplespigot.json.TypeTokens.findType(TypeTokens.java:10) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.storage.DailyQuestStorage.lambda$deserializer$3(DailyQuestStorage.java:42) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/me.hyfe.simplespigot.storage.storage.Storage.load(Storage.java:53) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.BattlePlugin.reloadDailyQuests(BattlePlugin.java:500) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.BattlePlugin.load(BattlePlugin.java:329) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:133) ~[BattlePass-4.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:40:26 INFO]: [BattlePass] Disabling BattlePass v4.6.1
[23:40:26 ERROR]: Error occurred while disabling BattlePass v4.6.1
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.quests.workers.reset.DailyQuestReset.getCurrentQuests()" because "<parameter1>" is null
        at BattlePass-4.6.1.jar/io.github.battlepass.storage.DailyQuestStorage.lambda$serializer$2(DailyQuestStorage.java:34) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/me.hyfe.simplespigot.storage.storage.Storage.save(Storage.java:57) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:372) ~[BattlePass-4.6.1.jar:?]
        at BattlePass-4.6.1.jar/io.github.battlepass.BattlePlugin.onDisable(BattlePlugin.java:154) ~[BattlePass-4.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### How to reproduce

This error occurs when the server starts, my server plugin list is as follows
`[23:45:20 INFO]: Paper Plugins: (3):
[23:45:20 INFO]:  - EconomyShopGUI-Premium, HuskHomes, HuskTowns
[23:45:20 INFO]: Bukkit Plugins: (31):
[23:45:20 INFO]:  - AntiPopup, BattlePass, Chunky, ChunkyBorder, Citizens, CMI, CMILib, DecentHolograms, DeluxeMenus, GSit
[23:45:20 INFO]:  ItemsAdder, LoneLibs, LuckPerms, MagicCosmetics, Multiverse-Core, PlaceholderAPI, PlayerPoints, PlayerTitle, PlugManX, ProtocolLib
[23:45:20 INFO]:  Quests, QuickShop-Hikari, SkinsRestorer, TAB-Bridge, TrChat, Vault, Veinminer, ViaVersion, WorldEdit, WorldGuard
[23:45:20 INFO]:  XConomy`

**Comment by KPGTB** [comment] 2024-08-01 17:48
Hey! Can you send me `daily-quests/daily-data.json` file? (or if you use mysql, `battlepass_daily-quests` table)

**Comment by KPGTB** [comment] 2024-08-03 12:44
Hey! I can't reproduce this error, but I made some changes in classes which caused this error and maybe after next update it will be fixed. After update, please install the latest version and let me know if it resolves your problem.

**Comment by cat-catmiao** [comment] 2024-08-04 04:40
This change seems to have worked, for can use the plugin properly now, thanks!

**Comment by cat-catmiao** [comment] 2024-08-04 04:46
I should add that at that time, when I deleted all the configuration files for bp, I could start and load bp normally, but when I didn't delete the configuration files for bp, the server started up with this error again, and I couldn't load the plugin. I didn't make any changes to bp's config files.

**Comment by cat-catmiao** [comment] 2024-08-04 04:48
`actions-version: 2

quests:
  1: # Quest id
    type: tame
    variable: wolf
    name: 'Dog Whisperer'
    required-progress: 5
    points: 10
    item:
      material: bone
      name: '&eDog Whisperer'
      lore:
        - '&7To complete this quest, you must'
        - '&7tame 5 wolves'
        - ''
        - '&7(&a%percentage_progress%&7)'
  2: # Quest id
    type: chat-stripped
    variable: how are you?
    name: 'Very Chatty'
    required-progress: 2
    points: 10
    item:
      material: paper
      name: '&eVery Chatty'
      lore:
        - '&7To complete this quest, you must'
        - '&7say "how are you?" in chat 2 times'
        - ''
        - '&7(&a%percentage_progress%&7'
  3: # Quest id
    type: gain-experience
    variable: none
    name: 'Magic Magnet'
    required-progress: 315
    points: 10
    item:
      material: book
      name: '&eMagic Magnet'
      lore:
        - '&7To complete this quest, you must'
        - '&7reach EXP level 15'
        - ''
        - '&7(&a%percentage_progress%&7)'
  4: # Quest id
    type: kill-player
    variable: none
    name: 'Murder Mystery'
    required-progress: 2
    points: 10
    item:
      material: stone_sword
      name: '&eMurder Mystery'
      lore:
        - '&7To complete this quest, you must'
        - '&7kill 2 players in pvp'
        - ''
        - '&7(&a%percentage_progress%&7)'
  5: # Quest id
    type: sprint
    variable: none
    name: 'Runner'
    required-progress: 2500
    points: 10
    item:
      material: leather_boots
      name: '&eMarathoner'
      lore:
        - '&7To complete this quest, you must'
        - '&7sprint over 2500 blocks.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  6: # Quest id
    type: throw-projectile
    variable: none
    name: 'Throw and Throw'
    required-progress: 200
    points: 10
    item:
      material: snowball
      name: '&eBaller'
      lore:
        - '&7To complete this quest, you must'
        - '&7throw/shoot 200 projectiles.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  7: # Quest id
    type: block-break
    variable: stone
    name: 'Miner'
    required-progress: 500
    points: 100
    item:
      material: cobblestone
      name: '&eMiner'
      lore:
        - '&7To complete this quest, you must'
        - '&7mine 500 stone blocks.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  8: # Quest id
    type: block-break
    variable: jungle_log OR jungle_wood
    name: 'Timber Man'
    required-progress: 350
    points: 10
    item:
      material: jungle_log
      name: '&eTimber Man'
      lore:
        - '&7To complete this quest, you must'
        - '&7mine over 350 jungle wood blocks or logs.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  9: # Quest id
    type: craft
    variable: ___SWORD # Anything that contains _SWORD
    name: 'Blacksmith'
    required-progress: 4
    points: 10
    item:
      material: iron_sword
      name: '&eBlacksmith'
      lore:
        - '&7To complete this quest, you must'
        - '&7craft 4 swords of any material.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  10:
    type: enchant-all
    variable:
      root: FEATHER_FALLING
      level: 2
    name: 'Fall Harder'
    required-progress: 1
    points: 10
    item:
      material: enchanting_table
      name: '&eFall Harder'
      lore:
        - '&7To complete this quest, you must'
        - '&7enchant boots with feather falling level 2.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  11:
    type: consume
    variable: enchanted_golden_apple
    name: 'Really Magical Apple'
    required-progress: 2
    points: 10
    item:
      material: enchanted_golden_apple
      name: '&eReally Magical Apple'
      lore:
        - '&7To complete this quest, you must'
        - '&7eat/consume 2 enchanted golden apples.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  12: # Quest id
    type: left-click
    variable: none
    name: 'Autoclicker'
    required-progress: 28200
    points: 10
    item:
      material: anvil:0
      name: '&eAutoclicker'
      lore:
        - '&7To complete this quest, you must'
        - '&7left click 28200 blocks.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  13: # Quest id
    type: chat-stripped
    variable: this is fun
    name: 'Very Chatty'
    required-progress: 1
    points: 10
    item:
      material: paper
      name: '&eVery Chatty'
      lore:
        - '&7To complete this quest, you must'
        - '&7say "this is fun" in chat.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  14: # Quest id
    type: regenerate
    variable: SATIATED
    name: 'Hunger Games'
    required-progress: 1
    points: 10
    item:
      material: cooked_beef
      name: '&eHunger Games'
      lore:
        - '&7To complete this quest, you must'
        - '&7eat food to fill your hunger and regen health.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  15: # Quest id
    type: shear
    variable: none
    name: 'Wooly Jumper'
    required-progress: 12
    points: 10
    item:
      material: white_wool
      name: '&eWooly Jumper'
      lore:
        - '&7To complete this quest, you must'
        - '&7shear 12 wild sheep.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  16: # Quest id
    type: swim
    variable: none
    name: 'Keep on swimmin'
    required-progress: 600
    points: 10
    item:
      material: water_bucket
      name: '&eKeep on swimmin'
      lore:
        - '&7To complete this quest, you must'
        - '&7swim 600 blocks of water'
        - ''
        - '&7(&a%percentage_progress%&7)'
  17: # Quest id
    type: block-break
    variable: grass_block OR dirt
    name: 'Dirty Day'
    required-progress: 333
    points: 10
    item:
      material: grass_block
      name: '&eDirty Day'
      lore:
        - '&7To complete this quest, you must'
        - '&7mine 333 blocks of dirt/grass'
        - ''
        - '&7(&a%percentage_progress%&7)'
  18: # Quest id
    type: bucket-place
    variable: lava_bucket
    name: 'Griefer'
    required-progress: 3
    points: 10
    item:
      material: lava_bucket
      name: '&eGriefer'
      lore:
        - '&7To complete this quest, you must'
        - '&7place 3 lava buckets'
        - ''
        - '&7(&a%percentage_progress%&7)'
  19: # Quest id
    type: fish
    variable: none
    name: 'Fish Catcher'
    required-progress: 3
    points: 10
    item:
      material: salmonmak
      name: '&eFish Catcher'
      lore:
        - '&7To complete this quest, you must'
        - '&7cacth 3 items/fish from fishing'
        - ''
        - '&7(&a%percentage_progress%&7)'
  20: # Quest id
    type: sneak
    variable: none
    name: 'Creepy Crawlie'
    required-progress: 55
    points: 10
    item:
      material: leather_boots
      name: '&eCreepy Crawlie'
      lore:
        - '&7To complete this quest, you must'
        - '&7sneak over 55 blocks in any direction'
        - ''
        - '&7(&a%percentage_progress%&7)'
  21: # Quest id
    type: kill-mob
    variable: cow
    name: 'Cow Killer'
    required-progress: 10
    points: 10
    item:
      material: leather
      name: '&eCow Killer'
      lore:
        - '&7To complete this quest, you must'
        - '&7kill 10 cows.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  22:
    type: glide
    variable: none
    name: 'Glider'
    required-progress: 150
    points: 10
    item:
      material: elytra
      name: '&eGlider'
      lore:
        - '&7To complete this quest, you must'
        - '&7glide over 150 blocks.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  23: # Quest id
    type: block-break
    variable:
      root: oak_log
    name: 'Lumberjack'
    required-progress: 50
    points: 10
    item:
      material: oak_log
      name: '&eLumberjack'
      lore:
        - '&7To complete this quest, you must'
        - '&7break 50 oak logs.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  24: # Quest id
    type: enchant-all
    variable:
      root: SHARPNESS
      level: 1
      item: diamond_sword
    name: 'Enchanter'
    required-progress: 1
    points: 10
    item:
      material: enchanting_table
      name: '&eEnchanter'
      lore:
        - '&7To complete this quest, you must'
        - '&7enchant a diamond sword with Sharpness 1'
        - '&7using an anvil or enchanting table.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  25: # Quest id
    type: fish
    variable: none
    name: 'Fisherman'
    required-progress: 10
    points: 10
    item:
      material: fishing_rod
      name: '&eFisherman'
      lore:
        - '&7To complete this quest, you must'
        - '&7successfully fish 10 times.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  26: # Quest id
    type: enchant-anvil
    variable:
      root: PROTECTION
      level: 1
      item: diamond_chestplate
    name: 'Protector'
    required-progress: 1
    points: 10
    item:
      material: diamond_chestplate
      name: '&eProtector'
      lore:
        - '&7To complete this quest, you must'
        - '&7enchant a diamond chestplate with Protection 1 using an anvil.'
        - ''
        - '&7(&a%percentage_progress%&7)'
  27: # Quest id
    type: smelt
    variable:
      root: iron_ingot
      amount: 10
    name: 'Smelter'
    required-progress: 10
    points: 10
    item:
      material: furnace
      name: '&eSmelter'
      lore:
        - '&7To complete this quest, you must'
        - '&7smelt 10 iron ingots.'
        - ''
        - '&7(&a%percentage_progress%&7)'
`
daily-quests.yml

**Comment by KPGTB** [comment] 2024-08-04 18:32
Okay, but is it working now or not?

**Comment by cat-catmiao** [comment] 2024-08-06 04:50
not work 。use 4.6.4
`[12:47:55 INFO]: [BattlePass] Successfully loaded the pass type with the id: free
[12:47:55 INFO]: [BattlePass] Successfully loaded the pass type with the id: premium
[12:47:55 ERROR]: Error occurred while enabling BattlePass v4.6.4 (Is it up to date?)
java.lang.IllegalArgumentException: TypeToken type argument must not contain a type variable; captured type variable T declared by public static java.lang.reflect.Type me.hyfe.simplespigot.json.TypeTokens.findType()
See https://github.com/google/gson/blob/main/Troubleshooting.md#typetoken-type-variable
        at com.google.gson.reflect.TypeToken.verifyNoTypeVariable(TypeToken.java:130) ~[gson-2.11.0.jar:?]
        at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:103) ~[gson-2.11.0.jar:?]
        at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:74) ~[gson-2.11.0.jar:?]
        at BattlePass-4.6.4.jar/me.hyfe.simplespigot.json.TypeTokens$1.<init>(TypeTokens.java:10) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/me.hyfe.simplespigot.json.TypeTokens.findType(TypeTokens.java:10) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.storage.DailyQuestStorage.lambda$deserializer$3(DailyQuestStorage.java:42) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/me.hyfe.simplespigot.storage.storage.Storage.load(Storage.java:53) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.BattlePlugin.reloadDailyQuests(BattlePlugin.java:501) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.BattlePlugin.load(BattlePlugin.java:329) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:133) ~[BattlePass-4.6.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:47:55 INFO]: [BattlePass] Disabling BattlePass v4.6.4
[12:47:55 ERROR]: Error occurred while disabling BattlePass v4.6.4
java.lang.NullPointerException: Cannot invoke "io.github.battlepass.quests.workers.reset.DailyQuestReset.getCurrentQuests()" because "<parameter1>" is null
        at BattlePass-4.6.4.jar/io.github.battlepass.storage.DailyQuestStorage.lambda$serializer$2(DailyQuestStorage.java:34) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/me.hyfe.simplespigot.storage.storage.Storage.save(Storage.java:57) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.BattlePlugin.unload(BattlePlugin.java:373) ~[BattlePass-4.6.4.jar:?]
        at BattlePass-4.6.4.jar/io.github.battlepass.BattlePlugin.onDisable(BattlePlugin.java:154) ~[BattlePass-4.6.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-d4fcc79]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
[latest.log](https://github.com/user-attachments/files/16505359/latest.log)

**Comment by cat-catmiao** [comment] 2024-08-06 04:51
It's very strange, when I delete all the config files for BP and I start the server, I can load BP normally, but if I restart the server, BP gets this error.

**Comment by KPGTB** [comment] 2024-08-06 07:16
Oh, it seems that GC didn't merge these changes yet. You need to wait. You can also try to remove folder `daily-data` and check if it works

**Comment by cat-catmiao** [comment] 2024-08-06 07:27
Deleting the daily-data does work, I can load BP, however, a new daily-data is generated and I shut down the server and when I start again, I can't load BP again!

**Comment by KPGTB** [comment] 2024-08-06 19:33
Please send me that file

**Comment by KPGTB** [comment] 2024-08-06 19:34
As I said, it should be fixed in the next update

**Comment by cat-catmiao** [comment] 2024-08-07 05:08
Got it. Thanks.

**Comment by KPGTB** [comment] 2024-08-07 19:16
check it now

**Closed** 2024-08-11 09:23 UTC
Labels: Bug: Unconfirmed, Status: Awaiting Response, Status: Testing in progress
