### ISSUE TITLE
[CRITICAL Issue] Data loss on restart

### ISSUE THREAD

**Issue by ireportbug** [GC-spigot/battle-pass#193] opened 2022-07-05 18:14 UTC
Server restart = Data loss (users folder reset it self)
Reload command = Data loss (users folder reset it self)

**Comment by GC-spigot** [comment] 2022-07-18 08:59
That doesn't happen for anyone but you. Can you run /bpdebug and show us the outcome? Sounds like a server issue, are you running it locally on your pc?

**Comment by ireportbug** [comment] 2022-07-19 13:43
its not important anymore im not gonna use that plugin, thanks.

**Comment by ireportbug** [comment] 2022-07-21 15:58
which one of you is a liar?

![1d](https://user-images.githubusercontent.com/108758489/180259633-0be4f959-fdfb-4bda-ad3c-3672c1afe7a8.png)

**Comment by ireportbug** [comment] 2022-07-22 11:54
Since you guys can not handle the truth;
cant get debug log because this plugin does not save anything.

**Comment by SirJben** [comment] 2022-07-23 07:38
Hi @GC-spigot. @ireportbug doesn't specify his server version in this report. 

He is using **1.8.8**, and when I tested this on a flat file and did the same thing that he instructed, I can confirm that it wasn't saving at all on my end. 

I used MySQL, which will save only in auto save 180 seconds on default (I also reduced it to 60s, and it saved) but stopping the server and not waiting on autosave, the quest will not save.

The jar that I used came from the AP website.

**Comment by GC-spigot** [comment] 2022-07-23 07:54
Can a config.yml be provided so I can test the exact situation?

**Comment by ireportbug** [comment] 2022-07-23 08:07
> Can a config.yml be provided so I can test the exact situation?
> […](#)
> On 2022-07-23, at 10:38 AM, SirJben ***@***.***> wrote: ﻿ Hi @GC-spigot. @ireportbug doesn't specify his server version in this report. He is using 1.8.8, and when I tested this on a flat file and did the same thing that he instructed, I can confirm that it wasn't saving at all on my end. I used MySQL, which will save only in auto save 180 seconds on default (I also reduced it to 60s, and it saved) but stopping the server and not waiting on autosave, the quest will not save. The jar that I used came from the AP website. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

use default :)

**Comment by SirJben** [comment] 2022-07-23 08:50
> Can a config.yml be provided so I can test the exact situation?
> […](#)
> On 2022-07-23, at 10:38 AM, SirJben ***@***.***> wrote: ﻿ Hi @GC-spigot. @ireportbug doesn't specify his server version in this report. He is using 1.8.8, and when I tested this on a flat file and did the same thing that he instructed, I can confirm that it wasn't saving at all on my end. I used MySQL, which will save only in auto save 180 seconds on default (I also reduced it to 60s, and it saved) but stopping the server and not waiting on autosave, the quest will not save. The jar that I used came from the AP website. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

It's the latest default config-generated BP folder on the 1.8.8 server version. [But sure this one](https://pastebin.com/PJ9fMtmG)

**Comment by Awpmeister2170** [comment] 2022-08-16 01:48
Not a Bug, Resolved in Ticket.

**Closed by Awpmeister2170** 2022-08-16 01:48 UTC
Labels: Issue
